version: "3.4"
services:
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 8005:8005
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true